# yazi.toml

[manager]
# 0/4 width for parent, 4/4 width for current, 0/4 width for preview
ratio = [0, 4, 0]

[opener]
edit = [
  { run = '~/.config/abyazelix/yazi/open-file.sh "$1"', desc = "Open File in a new pane" },
]
